[package]
name = "cefowldemo-macos-bindings"
version = "0.1.0"
edition = "2024"

[dependencies]

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-quartz-core = { workspace = true, features = ["CALayer"] }
